name: tipitaka
description: "Aplikasi myDhamma: Tipitaka Indonesia digital, referensi lengkap paritta dan sutta."
publish_to: 'none' 

# Versi Production
version: 4.1.2+85

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # Core & UI
  flutter_html: ^3.0.0
  flutter_custom_tabs: ^2.4.1
  flutter_svg: ^2.2.3
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.3.3
  scrollable_positioned_list: ^0.3.8
  
  # Network
  dio: ^5.9.0
  http: ^1.6.0  # (Cek catatan di bawah soal ini)
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2
  flutter_cache_manager: ^3.4.1 # untuk atthakatha tika
  
  # Logic & Data
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  html_unescape: ^2.0.0
  flutter_dotenv: ^6.0.0
  intl: ^0.20.0  # Tambahkan ini
  
  # Firebase
  firebase_core: ^4.3.0
  firebase_database: ^12.1.1
  
  # Sharing
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  gal: ^2.3.2
  auto_size_text_plus: ^3.0.2

  # Media
  audioplayers: ^6.5.1
  volume_controller: ^3.4.1 
  youtube_player_flutter: ^9.1.3
  path_provider: ^2.1.5
  html: ^0.15.6
  flutter_html_table: ^3.0.0
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Aset Offline (HTML/Web)
  assets:
    - assets/
    - assets/sounds/
    - assets/web/
    - assets/web/tem/
    - assets/web/abh/
    # Paritta Lain
    - assets/web/par/lain/
    - assets/web/par/lain/dbs/
    - assets/web/par/lain/dr/
    - assets/web/par/lain/patvdh/
    - assets/web/par/lain/yasati/
    # Paritta STI
    - assets/web/par/sti/
    - assets/web/par/sti/p1/
    - assets/web/par/sti/text/
    - assets/web/par/sti/text/paki/
    - assets/web/par/sti/text/raya/